name: Check with Discourse
on:
  workflow_dispatch:

jobs:
  check:
    name: Compare DOCS content with Discourse
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r discourse-sync/requirements.txt
      - name: Run discord-sync
        env:
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_API_USERNAME }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
          DOCS_DIR: ./DOCS
          TOPIC_IDS: ./topic-ids.yaml
        run: python ./discourse-sync/main.py check